name: mega_kinopoisk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  get_it: ^7.6.0
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.3
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  bloc: ^8.1.4
  build_runner: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.6.0


flutter:
  uses-material-design: true
  assets:
    - .env
